sudo: required
language: c

os: linux
dist: bionic
git:
  lfs_skip_smudge: true

install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt update
  - sudo apt install gcc-arm-embedded -y

jobs:
  include:
    - stage: "build"
      script:
      - TRAVIS_BUILD_DIR=apps/basic/ .travis/build_dir.sh
      - TRAVIS_BUILD_DIR=apps/thread/ .travis/build_dir.sh
      - TRAVIS_BUILD_DIR=apps/ble/ .travis/build_dir.sh
