sudo: required
language: c

os: linux
dist: bionic

install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt update
  - sudo apt install gcc-arm-embedded -y

jobs:
  include:
    - stage: basic
      script: TRAVIS_BUILD_DIR=apps/basic/ .travis/build_dir.sh
    - stage: thread
      script: TRAVIS_BUILD_DIR=apps/thread/ .travis/build_dir.sh
    - stage: ble
      script: TRAVIS_BUILD_DIR=apps/ble/ .travis/build_dir.sh
